# Boolean Indexing

In [2]:
import numpy as np

In [3]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [4]:
data = np.random.randn(7, 4)

In [5]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [6]:
data

array([[-1.30542498, -1.24780074, -0.59193452,  1.42745297],
       [-1.97068916,  0.31520298, -0.78595488, -0.11436485],
       [ 0.72602813, -1.470913  , -1.2609542 , -1.36996825],
       [-1.96945194,  0.59086927, -0.10926487, -0.76575758],
       [-1.05427098, -1.18042647,  0.78363468, -0.37508928],
       [-0.11918841,  0.59065331,  0.21061606,  0.50834685],
       [-0.65316904,  2.03505697, -0.17139418, -1.26408102]])

In [7]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [8]:
data[names == 'Bob']

array([[-1.30542498, -1.24780074, -0.59193452,  1.42745297],
       [-1.96945194,  0.59086927, -0.10926487, -0.76575758]])

In [9]:
data[names != 'Bob']

array([[-1.97068916,  0.31520298, -0.78595488, -0.11436485],
       [ 0.72602813, -1.470913  , -1.2609542 , -1.36996825],
       [-1.05427098, -1.18042647,  0.78363468, -0.37508928],
       [-0.11918841,  0.59065331,  0.21061606,  0.50834685],
       [-0.65316904,  2.03505697, -0.17139418, -1.26408102]])

In [12]:
data[names == 'Bob', 1:3]

array([[-1.24780074, -0.59193452],
       [ 0.59086927, -0.10926487]])

In [11]:
data

array([[-1.30542498, -1.24780074, -0.59193452,  1.42745297],
       [-1.97068916,  0.31520298, -0.78595488, -0.11436485],
       [ 0.72602813, -1.470913  , -1.2609542 , -1.36996825],
       [-1.96945194,  0.59086927, -0.10926487, -0.76575758],
       [-1.05427098, -1.18042647,  0.78363468, -0.37508928],
       [-0.11918841,  0.59065331,  0.21061606,  0.50834685],
       [-0.65316904,  2.03505697, -0.17139418, -1.26408102]])

In [13]:
data[3]

array([-1.96945194,  0.59086927, -0.10926487, -0.76575758])

In [14]:
data[[3,4,0,1]]

array([[-1.96945194,  0.59086927, -0.10926487, -0.76575758],
       [-1.05427098, -1.18042647,  0.78363468, -0.37508928],
       [-1.30542498, -1.24780074, -0.59193452,  1.42745297],
       [-1.97068916,  0.31520298, -0.78595488, -0.11436485]])

In [15]:
cond = names == 'Bob'

In [16]:
cond

array([ True, False, False,  True, False, False, False])

In [19]:
data[~(cond)]

array([[-1.97068916,  0.31520298, -0.78595488, -0.11436485],
       [ 0.72602813, -1.470913  , -1.2609542 , -1.36996825],
       [-1.05427098, -1.18042647,  0.78363468, -0.37508928],
       [-0.11918841,  0.59065331,  0.21061606,  0.50834685],
       [-0.65316904,  2.03505697, -0.17139418, -1.26408102]])

In [25]:
mask = (names == 'Bob') | (names == 'Will')

In [21]:
mask

array([ True, False,  True,  True,  True, False, False])

In [22]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [23]:
data[mask]

array([[-1.30542498, -1.24780074, -0.59193452,  1.42745297],
       [ 0.72602813, -1.470913  , -1.2609542 , -1.36996825],
       [-1.96945194,  0.59086927, -0.10926487, -0.76575758],
       [-1.05427098, -1.18042647,  0.78363468, -0.37508928]])

In [26]:
data < 0

array([[ True,  True,  True, False],
       [ True, False,  True,  True],
       [False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True, False, False, False],
       [ True, False,  True,  True]])

In [27]:
data[data < 0]

array([-1.30542498, -1.24780074, -0.59193452, -1.97068916, -0.78595488,
       -0.11436485, -1.470913  , -1.2609542 , -1.36996825, -1.96945194,
       -0.10926487, -0.76575758, -1.05427098, -1.18042647, -0.37508928,
       -0.11918841, -0.65316904, -0.17139418, -1.26408102])

In [28]:
data[data < 0] = 0

In [29]:
data

array([[0.        , 0.        , 0.        , 1.42745297],
       [0.        , 0.31520298, 0.        , 0.        ],
       [0.72602813, 0.        , 0.        , 0.        ],
       [0.        , 0.59086927, 0.        , 0.        ],
       [0.        , 0.        , 0.78363468, 0.        ],
       [0.        , 0.59065331, 0.21061606, 0.50834685],
       [0.        , 2.03505697, 0.        , 0.        ]])

# Fancy Indexing

In [30]:
arr = np.empty((8, 4))

In [31]:
for i in range(8):
    arr[i] = i

In [32]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [36]:
arr[4]

array([4., 4., 4., 4.])

In [37]:
arr[[4,6]]

array([[4., 4., 4., 4.],
       [6., 6., 6., 6.]])

In [41]:
arr[[4,6], 2:]

array([[4., 4.],
       [6., 6.]])

In [42]:
arr = np.arange(32).reshape((8, 4))

In [43]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [44]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [46]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [45]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

#1[0,3,1,2], 5[0,3,1,2], 7[0,3,1,2], 2[0,3,1,2]
#[(1,0),(1,3),(1,1),(1,2)] and so on

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

# Transposing Arrays and Swapping Axes

In [47]:
arr = np.arange(15).reshape((3, 5))

In [48]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [49]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [50]:
arr = np.random.randn(7) * 5

In [51]:
arr

array([-2.74047054,  5.94930977, -3.39645448,  0.55494618,  4.17097356,
        3.44623831, -0.29287292])

In [52]:
remainder, whole_part = np.modf(arr)

In [53]:
remainder

array([-0.74047054,  0.94930977, -0.39645448,  0.55494618,  0.17097356,
        0.44623831, -0.29287292])

In [54]:
whole_part

array([-2.,  5., -3.,  0.,  4.,  3., -0.])

# Array-Oriented Programming with Arrays

In [55]:
names = ['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']

In [57]:
names

['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']

In [58]:
names = set(names)

In [59]:
names

{'Bob', 'Joe', 'Will'}

In [60]:
students = {'Ali','Nasir','Mohsin', 'Ali'}

In [61]:
students

{'Ali', 'Mohsin', 'Nasir'}

In [67]:
arr = np.arange(24)

In [71]:
arr.reshape((4, -1))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [88]:
arr = np.arange(15).reshape((5, 3))

In [73]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [74]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [75]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [76]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [89]:
flat = arr.flatten()

In [78]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [81]:
ravel = arr.ravel()

In [80]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [83]:
ravel

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [90]:
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [85]:
ravel[2:8] = 0

In [86]:
ravel

array([ 0,  1,  0,  0,  0,  0,  0,  0,  8,  9, 10, 11, 12, 13, 14])

In [87]:
arr

array([[ 0,  1,  0],
       [ 0,  0,  0],
       [ 0,  0,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [91]:
flat[2:8] = 0

In [92]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [94]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:

arr2 = np.array([[7, 8, 9], [10, 11, 12]])
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [97]:
np.concatenate([arr1,arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [98]:
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [99]:
np.concatenate([arr1,arr2],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [100]:
splitt =np.arange(1,25).reshape(6,4)
splitt

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [104]:
np.vsplit(splitt,2)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]), array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [106]:
np.hsplit(splitt,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]), array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

In [110]:
arr=np.array([1,2,3,4])
a=np.broadcast(arr,4)

In [111]:
a