In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import tensorflow

In [4]:
from tensorflow.keras.datasets import mnist

In [5]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [6]:
train_images.shape

(60000, 28, 28)

In [7]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [8]:
len(train_labels)

60000

In [9]:
from tensorflow.keras import models

In [10]:
from tensorflow.keras import layers

In [11]:
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

In [12]:
network.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])

In [13]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [14]:
from tensorflow.keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [15]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 10s 165us/sample - loss: 0.2597 - accuracy: 0.9244
Epoch 2/5
60000/60000 [==============================] - 7s 124us/sample - loss: 0.1040 - accuracy: 0.9696
Epoch 3/5
60000/60000 [==============================] - 7s 122us/sample - loss: 0.0679 - accuracy: 0.9796
Epoch 4/5
60000/60000 [==============================] - 7s 123us/sample - loss: 0.0496 - accuracy: 0.9850
Epoch 5/5
60000/60000 [==============================] - 7s 124us/sample - loss: 0.0370 - accuracy: 0.9891


In [16]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc:', test_acc)

10000/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

test_acc: 0.9783


In [17]:
network.fit(train_images, train_labels, epochs=10, batch_size=128)

Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 7s 124us/sample - loss: 0.0287 - accuracy: 0.9915
Epoch 2/10
60000/60000 [==============================] - 7s 123us/sample - loss: 0.0210 - accuracy: 0.9939
Epoch 3/10
60000/60000 [==============================] - 8s 130us/sample - loss: 0.0171 - accuracy: 0.9948
Epoch 4/10
60000/60000 [==============================] - 10s 164us/sample - loss: 0.0128 - accuracy: 0.9963
Epoch 5/10
60000/60000 [==============================] - 8s 138us/sample - loss: 0.0103 - accuracy: 0.9971
Epoch 6/10
60000/60000 [==============================] - 8s 128us/sample - loss: 0.0077 - accuracy: 0.9979
Epoch 7/10
60000/60000 [==============================] - 8s 131us/sample - loss: 0.0061 - accuracy: 0.9983
Epoch 8/10
60000/60000 [==============================] - 8s 127us/sample - loss: 0.0046 - accuracy: 0.9987
Epoch 9/10
60000/60000 [==============================] - 7s 118us/sample - loss: 0.0038 - accuracy: 0.9987
Epoc

In [18]:
x = np.array(12)

In [19]:
x

array(12)

In [20]:
x = np.array([12, 3, 6, 14])
x

array([12,  3,  6, 14])

In [21]:
x.ndim

1

In [22]:
x = np.array([[5, 78, 2, 34, 0],[6, 79, 3, 35, 1],[7, 80, 4, 36, 2]])

In [23]:
x

array([[ 5, 78,  2, 34,  0],
       [ 6, 79,  3, 35,  1],
       [ 7, 80,  4, 36,  2]])

In [24]:
x = np.array([[[5,[6,[7,[[5,[6,[7,[[5,[6,[7,3,78,79,80,78,79,80,78,79,80,2,3,4,2,3,4,2,3,4,34,35,36,34,35,36,34,35,36,0],1],2]],0],1],2]],0],1],2]]])

In [25]:
x

array([[[5,
         list([6, [7, [[5, [6, [7, [[5, [6, [7, 3, 78, 79, 80, 78, 79, 80, 78, 79, 80, 2, 3, 4, 2, 3, 4, 2, 3, 4, 34, 35, 36, 34, 35, 36, 34, 35, 36, 0], 1], 2]], 0], 1], 2]], 0], 1]),
         2]]], dtype=object)